### ISSUE TITLE
No support for teacher view

### ISSUE THREAD

**Issue by ArtrenH** [ArtrenH/VPlan_FR#48] opened 2023-07-14 23:19 UTC
If someone had a teacher password, it would be useful to get access to actual teacher and room information

**Comment by Belissimo-T** [comment] 2023-07-18 08:52
Do we always want to display the teacher room information or the extracted data from the form plan? Maybe offer both and provide a toggle switch?

**Comment by ArtrenH** [comment] 2023-10-02 15:50
Isn't this finished with the fix of #81

**Comment by Belissimo-T** [comment] 2023-10-03 17:25
@ArtrenH #81 was a duplicate of this issue. I closed it as "not planned".
This issue is fixed however because of commits 26578177 and cc15ee18.

**Closed by Belissimo-T** 2023-10-03 17:25 UTC
Labels: enhancement, plan loader
